version: "3.9"

services:
  wasp-discord:
    container_name: "wasp-discord"
    build:
      context: .
      args:
        BOT_TOKEN: $BOT_TOKEN
        GUILD_ID: $GUILD_ID
        SB_URL: $SB_URL
        SB_ANON_KEY: $SB_ANON_KEY
        SERVICE_USER: $SERVICE_USER
        SERVICE_PASS: $SERVICE_PASS
        ENVIRONMENT: $ENVIRONMENT
    restart: unless-stopped
    volumes:
      - /docker/etc/letsencrypt/live/waspscripts.com/cert.pem:/etc/letsencrypt/live/waspscripts.com/cert.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/fullchain.pem:/etc/letsencrypt/live/waspscripts.com/fullchain.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/privkey.pem:/etc/letsencrypt/live/waspscripts.com/privkey.pem
    networks:
      - hive
    env_file:
      - .env

networks:
  hive:
    external: true
